Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "generic/ubuntu1604"
  c.vm.hostname = "default2-ubuntu-1604.vagrantup.com"
  c.vm.network(:forwarded_port, {:guest=>80, :host=>8081})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :libvirt do |p|
  end
end
